modLoader="javafml"
license="ARR"

[[mods]]
modId="streq"
version="1.0.7"
displayName="StrEq"
authors="Banduty"
description='''String to Equation!'''

[["streq"]]
modId="forge"
mandatory=true
ordering="NONE"
side="BOTH"

[["streq"]]
modId="minecraft"
mandatory=true

ordering="NONE"
side="BOTH"