modLoader="javafml"
loaderVersion="[0,)"
license="All Rights Reserved"

[[mods]]
modId="streq"
version="1.0.8"
displayName="StrEq"
authors="Banduty"
description='''String to Equation!'''

logoFile="assets/streq/logo.png"
displayURL=""
issueTrackerURL=""
updateJSONURL=""

# Dependency configuration
[[dependencies.streq]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"