modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://discord.gg/vbZ2zTHGNA"
logoFile="StrEq.png"

[[mods]]
modId="streq"
version="1.0.1"
displayName="StrEq"
displayURL=""
authors="Banduty"
description='''String to Equation!'''
credits=''''''

[[dependencies.streq]]
modId="minecraft"
type="required"
versionRange=">=1.17"
ordering="NONE"
side="BOTH"