modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://discord.gg/vbZ2zTHGNA"
logoFile=""

[[mods]]
modId="streq"
version="1.0.5"
displayName="StrEq"
displayURL=""
authors="Banduty"
description='''String to Equation!'''
credits=''''''